<a href="https://colab.research.google.com/github/mariamjajurie/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

##<b> Part 1: Matrices and Linear Equations </b>

1. Given the linear combination below, try to create a corresponding matrix representing it.

:$$\theta = 5x + 3y - z$$

\begin{bmatrix} 5 & 3 & {-1}\end{bmatrix} \\


<b> Given the matrix below, express it as a linear combination in a markdown and a LaTeX markdown </b>


In [ ]:
G = np.array([
    [1,7,8],
    [2,2,2],
    [4,6,7]
])

\begin{bmatrix} 1 & 7 & 8 \\ 2 & 2 & 2 \\ 4 & 6 & 7 \end{bmatrix}

$$
G = \left\{\begin{array}
1x + 7y +8\\
2x + 2y + 2\\
4x + 6y + 7
\end{array}\right.
$$

<b> 2. Given the system of linear combinations below, try to encode it as a matrix. Also describe the matrix. </b>

$$
A = \left\{\begin{array}
5x_1 + 2x_2 +x_3\\
4x_2 - x_3\\
10x_3
\end{array}\right.
$$

In [ ]:
def mat_desc(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
      print('Matrix is Null')

A = np.array([
    [1,2,3],
    [0,4,-1],
    [0, 0,10]
])
mat_desc(A)

Matrix:
[[ 1  2  3]
 [ 0  4 -1]
 [ 0  0 10]]

Shape:	(3, 3)
Rank:	2
Is Square: True



Given the matrix below, display the output as a LaTeX markdown also express it as a system of linear combinations.

In [ ]:
H = np.tril(G)
H

array([[1, 0, 0],
       [2, 2, 0],
       [4, 6, 7]])

\begin{bmatrix} 1 & 0 & 0 \\ 2 & 2 & 0 \\ 4 & 6 & 7 \end{bmatrix}

$$
H = \left\{\begin{array}
1x \\
2x + 2y \\
4x + 6y + 7
\end{array}\right.
$$

##<b> Part 2.1: Matrix Categories </b>

In [2]:
def mat_desc(mat):
    sq = False
    mat = np.array(mat)
    print(mat)
    print('Shape:', mat.shape)
    print('Size:', mat.size)
    print('Rank:', np.linalg.matrix_rank(mat))
    if(mat.shape[0] == mat.shape[1]):
        sq = True
        print('The matrix is square')
    else:
        print('The matrix is non-square')
    if(mat.shape[0] == 0 and mat.shape[1] == 0):
        print('The matrix is empty')
    else:
        print('The matrix is not empty')
    iden = np.identity(mat.shape[0])
    if(sq and (iden == mat).all()):
        print('The matrix is an identity matrix')
    else:
        print('The matrix is not an identity matrix')
    one = np.ones((mat.shape[0], mat.shape[1]))
    if((one == mat).all()):
        print('The matrix is an ones matrix')
    else:
        print('The matrix is not an ones matrix')
    zero = np.zeros((mat.shape[0], mat.shape[1]))
    if((zero == mat).all()):
        print('The matrix is an zeros matrix\n')
    else:
        print('The matrix is not a zeros matrix\n')

In [1]:
import numpy as np
A = np.array([
          [0,2,2,3],
          [1,0,2,4],
          [1,2,0,6],
          [1,2,1,3] 
])

B = np.array([
    [1,2,6],
    [4,0,3],
    [8,1,9]
])

F = np.array([
              [2,4,7,1,8],
              [7,8,2,9,6],
              [1,2,3,4,5],
              [6,7,8,9,1]
])

X = np.array([
              [1,1,1,7],
              [1,0,1,2],
              [1,1,2,6]
])
Y = np.array([
              [4,7,8,4],
              [3,7,8,9],
              [3,8,1,6]
])



In [3]:
mat_desc(A)
mat_desc(B)
mat_desc(F)
mat_desc(X)
mat_desc(Y)

[[0 2 2 3]
 [1 0 2 4]
 [1 2 0 6]
 [1 2 1 3]]
Shape: (4, 4)
Size: 16
Rank: 4
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix

[[1 2 6]
 [4 0 3]
 [8 1 9]]
Shape: (3, 3)
Size: 9
Rank: 3
The matrix is square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix

[[2 4 7 1 8]
 [7 8 2 9 6]
 [1 2 3 4 5]
 [6 7 8 9 1]]
Shape: (4, 5)
Size: 20
Rank: 4
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix

[[1 1 1 7]
 [1 0 1 2]
 [1 1 2 6]]
Shape: (3, 4)
Size: 12
Rank: 3
The matrix is non-square
The matrix is not empty
The matrix is not an identity matrix
The matrix is not an ones matrix
The matrix is not a zeros matrix

[[4 7 8 4]
 [3 7 8 9]
 [3 8 1 6]]
Shape: (3, 4)
Size: 12
Rank: 3
The matrix is non-square
The matrix is not empty

##<b> Part 2.2: Matrix Algebra </b>

In [5]:
def mat_operations(matrix1, matrix2): 
  while True:
   try:
    sum = np.add(matrix1, matrix2) 
    print(f'Sum: \n{sum}\n')
    break
   except: ValueError
   print('Sum: undefined\n') 
   break
  while True: 
    try:
     difference = np.subtract(matrix1, matrix2) 
     print(f'Difference: \n{difference}\n')
     break
    except: ValueError
    print('Difference: undefined\n')
    break
  while True:
    try:
      elem_wise_mul = np.multiply(matrix1,matrix2)
      print(f'Elem-wise multiplication: \n{elem_wise_mul}\n')
      break
    except: ValueError
    print('Elem-wise multiplication: undefined\n')
    break
  while True:
    try:
      elem_wise_div = np.divide(matrix1,matrix2)
      print(f'Elem-wise divide: \n{elem_wise_div}\n')
      break
    except: ValueError
    print('Elem-wise divide: undefined\n')
    break

In [6]:
import numpy as np
A = np.array([
    [2,2,3],
    [1,2,9],
    [8,1,4]
])

B = np.array([
    [1,2,6],
    [4,2,3],
    [8,1,9]
])

N = np.array([
              [5,2,7,4],
              [8,6,2,5],
              [2,3,2,8],
              [3,5,4,2]
])

T = np.array([
    [6,2,8],
    [8,1,2],
    [7,1,9]
])

Z = np.array([
    [1,2,6],
    [4,6,3],
    [8,1,9]
])


In [ ]:
mat_operations(A,B)

Sum: 
[[ 3  4  9]
 [ 5  4 12]
 [16  2 13]]

Difference: 
[[ 1  0 -3]
 [-3  0  6]
 [ 0  0 -5]]

Elem-wise multiplication: 
[[ 2  4 18]
 [ 4  4 27]
 [64  1 36]]

Elem-wise divide: 
[[2.         1.         0.5       ]
 [0.25       1.         3.        ]
 [1.         1.         0.44444444]]



In [ ]:
mat_operations(T,Z)

Sum: 
[[ 7  4 14]
 [12  7  5]
 [15  2 18]]

Difference: 
[[ 5  0  2]
 [ 4 -5 -1]
 [-1  0  0]]

Elem-wise multiplication: 
[[ 6  4 48]
 [32  6  6]
 [56  1 81]]

Elem-wise divide: 
[[6.         1.         1.33333333]
 [2.         0.16666667 0.66666667]
 [0.875      1.         1.        ]]



In [ ]:
mat_operations(A,Z)

Sum: 
[[ 3  4  9]
 [ 5  8 12]
 [16  2 13]]

Difference: 
[[ 1  0 -3]
 [-3 -4  6]
 [ 0  0 -5]]

Elem-wise multiplication: 
[[ 2  4 18]
 [ 4 12 27]
 [64  1 36]]

Elem-wise divide: 
[[2.         1.         0.5       ]
 [0.25       0.33333333 3.        ]
 [1.         1.         0.44444444]]



In [7]:
mat_operations(N,T)

Sum: undefined

Difference: undefined

Elem-wise multiplication: undefined

Elem-wise divide: undefined



In [8]:
mat_operations(T,B)

Sum: 
[[ 7  4 14]
 [12  3  5]
 [15  2 18]]

Difference: 
[[ 5  0  2]
 [ 4 -1 -1]
 [-1  0  0]]

Elem-wise multiplication: 
[[ 6  4 48]
 [32  2  6]
 [56  1 81]]

Elem-wise divide: 
[[6.         1.         1.33333333]
 [2.         0.5        0.66666667]
 [0.875      1.         1.        ]]

