<a href="https://colab.research.google.com/github/mariamjajurie/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/assignment_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#<b>matrix multiplication properties</b>


Prove and implement the remaining 6 matrix multiplication properties. You may create your own matrices in which their shapes should not be lower than 
(3,3)
. In your methodology, create individual flowcharts for each property and discuss the property you would then present your proofs or validity of your implementation in the results section by comparing your result to present functions from NumPy.


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

 ### 1. $A \cdot B \neq B \cdot A$

In [ ]:
B = np.array([
    [1,2,6],
    [4,0,3],
    [8,1,9]
])
Y = np.array([
              [4,7,8],
              [3,7,8],
              [3,8,1]
])


In [ ]:
T = B@Y
T

array([[ 28,  69,  30],
       [ 25,  52,  35],
       [ 62, 135,  81]])

In [ ]:
Z = Y@B
Z

array([[ 96,  16, 117],
       [ 95,  14, 111],
       [ 43,   7,  51]])

In [ ]:
np.array_equiv(T,Z)

False

###2. $A \cdot (B \cdot C) = (A \cdot B) \cdot C$
####associative property

In [ ]:
C = np.array([
              [1,1,1,7],
              [1,0,1,2],
              [1,1,2,6]
])

D = np.array([
              [1,3,4],
              [6,3,8],
              [3,2,9],
              [2,6,7]
])

E = np.array([
              [5,2,3],
              [7,5,4],
              [1,3,5]    
])

In [ ]:
J = C@(D@E)
J

array([[540, 508, 622],
       [186, 182, 227],
       [519, 496, 619]])

In [ ]:
K = (C@D)@E
K

array([[540, 508, 622],
       [186, 182, 227],
       [519, 496, 619]])

In [ ]:
np.array_equiv(J,K)

True

### 3. $A\cdot(B+C) = A\cdot B + A\cdot C$
####distributive property

In [ ]:
F = np.array([
              [7,1,8],
              [2,9,6],
              [3,4,5],
              [8,9,1]
])

C = np.array([
              [1,1,1,7],
              [1,0,1,2],
              [1,1,2,6]
])

D = np.array([
              [1,3,4,2],
              [6,3,8,3],
              [3,2,9,4],
])

In [ ]:
L = F@(C+D)
L

array([[ 53,  55, 132, 148],
       [ 91,  53, 157, 123],
       [ 54,  39, 106,  97],
       [ 83,  62, 132, 127]])

In [ ]:
M = (F@C) + (F@D)
M

array([[ 53,  55, 132, 148],
       [ 91,  53, 157, 123],
       [ 54,  39, 106,  97],
       [ 83,  62, 132, 127]])

In [ ]:
np.array_equiv(L,M)

True

### 4. $(B+C)\cdot A = B\cdot A + C\cdot A$
####distributive property

In [ ]:
F = np.array([
              [7,1,8],
              [2,9,6],
              [3,4,5],
              [8,9,1]
])

C = np.array([
              [1,1,1,7],
              [1,0,1,2],
              [1,1,2,6]
])

D = np.array([
              [1,3,4,2],
              [6,3,8,3],
              [3,2,9,4],
])

In [ ]:
N = (C+D)@F
N

array([[109, 139,  74],
       [122, 115, 124],
       [147, 165, 115]])

In [ ]:
P = (C@F) + (D@F)
P

array([[109, 139,  74],
       [122, 115, 124],
       [147, 165, 115]])

In [ ]:
np.array_equiv(N,P)

True

### 5. $A\cdot \emptyset = \emptyset$ 
####zero matrix property

In [ ]:
A = np.array([
          [0,2,2,3],
          [1,0,2,4],
          [1,2,0,6],
          [1,2,1,3] 
])

O = np.zeros((4,4))

In [ ]:
A@O

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])